set(COMBO_ENABLE ON CACHE BOOL "KB" FORCE)
set(LEADER_ENABLE ON CACHE BOOL "KB" FORCE)
set(DYNAMIC_MACRO_ENABLE ON CACHE BOOL "KB" FORCE)

list(APPEND QMK_PORTING_SOURCES
    "${QMK_BASE_DIR}/users/rgoulter/rgoulter.c"
)
