set(MOUSE_ENABLE ON CACHE BOOL "KB" FORCE)
set(NKRO_ENABLE ON CACHE BOOL "KB" FORCE)
set(ENCODER_MAP_ENABLE ON CACHE BOOL "KB" FORCE)
set(VIA_ENABLE OFF CACHE BOOL "KB" FORCE)
set(BOOTMAGIC_ENABLE ON CACHE BOOL "KB" FORCE)
set(COMMAND_ENABLE ON CACHE BOOL "KB" FORCE)

set(EEPROM_DRIVER "custom" CACHE STRING "KB" FORCE)

set(USB_ENABLE ON CACHE BOOL "KB" FORCE)
